
export var locationObj = {
    'France': {
        'name': ['Eiffel Tower', 'Musée du Louvre', 'Château de Versailles', 'Côte dAzur', 'Mont Saint-Michel'], 
        'description': ["The Eiffel Tower is a wrought-iron lattice tower on the Champ de Mars in Paris, France. It is named after the engineer Gustave Eiffel, whose company designed and built the tower.", "The Louvre, or the Louvre Museum, is the world's most-visited museum, and a historic landmark in Paris, France. It is the home of some of the best-known works of art, including the Mona Lisa and the Venus de Milo.", "The Palace of Versailles has been listed as a World Heritage Site for 40 years and is one of the greatest achievements in French 17th century art. Louis XIII's old hunting pavilion was transformed and extended by his son, Louis XIV, when he installed the Court and government there in 1682. A succession of kings continued to embellish the Palace up until the French Revolution.", "The French Riviera (or Côte d'Azur) is the Mediterranean coast of southeastern France. It includes famously glamorous beach resorts such as Saint-Tropez and Cannes, and the independent microstate of Monaco. A health retreat in the 18th century, the area later attracted aristocrats, artists and the 1960s jet set. Today it’s an established holiday destination, with paths connecting many coastal villages and towns.", "Le Mont-Saint-Michel is a tidal island and mainland commune in Normandy, France. The island lies approximately one kilometre off the country's north-western coast, at the mouth of the Couesnon River near Avranches and is 7 hectares in area."], 
        'image': ['https://images.pexels.com/photos/161853/eiffel-tower-paris-france-tower-161853.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 'https://images.pexels.com/photos/2363/france-landmark-lights-night.jpg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 'https://images.pexels.com/photos/206762/pexels-photo-206762.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 'https://images.pexels.com/photos/4245819/pexels-photo-4245819.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 'https://images.pexels.com/photos/34223/mont-saint-michel-france-normandy-europe.jpg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940'], 
    }, 

    'Spain': {
        'name': ['The Alhambra and Generalife Gardens', "Barcelona's Sagrada Familia and Gaudi Sites", 'The Great Mosque of Cordoba', 'The Prado and Paseo del Artes', 'Seville Cathedral and Alcazar'], 
        'description': ["The Generalife is a former palace and country estate built by the Muslim Conquerers who occupied parts of the Iberian peninsula from the 8th century onwards. It forms part of the conjunct of buildings which include the world-famous Alhambra and Albayzín in the Spanish town of Granada.", "The expiatory temple of the Sagrada Familia, the construction of which commenced in 1882, is today one of the emblems of Barcelona, known around the world and visited by millions of people. The part built by Gaudí was declared a UNESCO World Heritage Site in 2005.", "The Mosque–Cathedral of Córdoba, officially known by its ecclesiastical name, the Cathedral of Our Lady of the Assumption, is the cathedral of the Roman Catholic Diocese of Córdoba dedicated to the Assumption of Mary and located in the Spanish region of Andalusia.", "This area, known in English as the Art Walk, boasts art and beauty as you’ll see nowhere else in the world. Along a stretch of just over one kilometre, you’ll find the Prado Museum, the Thyssen-Bornemisza Museum and the Reina Sofía Museum, as well as a number of other institutions and buildings well worth visiting. If you're planning on visiting all three museums, we recommend you purchase the Paseo del Arte pass (30.40€ in 2021) which is valid for one year and allows one visit to the permanent collection of each of the three museums.", "The Cathedral of Saint Mary of the See, better known as Seville Cathedral, is a Roman Catholic cathedral in Seville, Andalusia, Spain. It was registered in 1987 by UNESCO as a World Heritage Site, along with the adjoining Alcázar palace complex and the General Archive of the Indies."], 
        'image': ['https://images.pexels.com/photos/2431436/pexels-photo-2431436.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500', 'https://images.pexels.com/photos/1386444/pexels-photo-1386444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 'https://images.pexels.com/photos/7861201/pexels-photo-7861201.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500', 'https://images.pexels.com/photos/5630838/pexels-photo-5630838.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 'https://images.pexels.com/photos/2422461/pexels-photo-2422461.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940'], 
    }, 

    'United States': {
        'name': ['Mount Rushmore', 'Kennedy Space Center', 'Navy Pier in Chicago', 'Bryce Canyon National Park', 'French Quarter in New Orleans'], 
        'description': ["Mount Rushmore National Memorial is a massive sculpture carved into Mount Rushmore in the Black Hills region of South Dakota. Completed in 1941 under the direction of Gutzon Borglum and his son Lincoln, the sculpture's roughly 60-ft.-high granite faces depict U.S. presidents George Washington, Thomas Jefferson, Theodore Roosevelt and Abraham Lincoln. The site also features a museum with interactive exhibits.", "Kennedy Space Center (KSC, originally known as the NASA Launch Operations Center), located on Merritt Island, Florida, is one of the National Aeronautics and Space Administration's (NASA) ten field centers. Since December 1968, KSC has been NASA's primary launch center of human spaceflight.", "Navy Pier is a 3,300-foot-long (1,010 m) pier on the shoreline of Lake Michigan, located in the Streeterville neighborhood of the Near North Side community area in Chicago, Illinois, United States. ... It is one of the most visited attractions in the entire Midwest and is Chicago's second-most visited tourist attraction.", "Bryce Canyon National Park, a sprawling reserve in southern Utah, is known for crimson-colored hoodoos, which are spire-shaped rock formations. The park’s main road leads past the expansive Bryce Amphitheater, a hoodoo-filled depression lying below the Rim Trail hiking path. It has overlooks at Sunrise Point, Sunset Point, Inspiration Point and Bryce Point. Prime viewing times are around sunup and sundown.", "The French Quarter is the city’s historic heart, famous for its vibrant nightlife and colorful buildings with cast-iron balconies. Crowd-pleasing Bourbon Street features jazz clubs, Cajun eateries and raucous bars serving potent cocktails. Quieter streets lead to the French Market, with gourmet food and local crafts, and to Jackson Square where street performers entertain in front of soaring St. Louis Cathedral."], 
        'image': ['https://images.pexels.com/photos/136154/pexels-photo-136154.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 'https://images.pexels.com/photos/5847359/pexels-photo-5847359.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 'https://images.pexels.com/photos/8387648/pexels-photo-8387648.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500', 'https://images.pexels.com/photos/8909778/pexels-photo-8909778.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500', 'https://images.pexels.com/photos/6379409/pexels-photo-6379409.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940'], 
    }, 

    'China': {
        'name': ['The Great Wall of China', 'The Forbidden City & the Imperial Palace', 'The Summer Palace', 'Cruising the Li River', 'The Yangtze River and the Three Gorges'], 
        'description': ["The Great Wall of China is a series of fortifications that were built across the historical northern borders of ancient Chinese states and Imperial China as protection against various nomadic groups from the Eurasian Steppe. ", "The Palace Museum is a national museum housed in the Forbidden City at the core of Beijing. It was established in 1925 after the last Emperor of China was evicted from his palace, and opened its doors to the public. Constructed from 1406 to 1420, the museum consists of 980 buildings and covers 72 hectares.", "The Summer Palace (Yiheyuan), in northwest Beijing, is said to be the best-preserved imperial garden in the world, and the largest of its kind still in existence in China. It is only a short drive of 15 km (10 miles) from central Beijing, but it seems like another world.Most people find they need to spend at least half a day there, as there’s so much to see and enjoy.Close to the Summer Palace, 3 kilometers (2 miles) southwest of it, there is another imperial garden called the Old Summer Palace. They are two different gardens.", "The Li River, or Li Jiang, is in Guilin, in South China’s Guangxi Province. It is renowned as being one of “the world’s top 10 watery wonders” according to National Geographic. The Li River cruise from Guilin to Yangshuo boasts the most beautiful scenery. Along the 86-kilometer waterway, you will see karst peaks, grazing water buffalo, farmers working in the fields, and traditional villages nestled at the bases of the hills.", "The Three Gorges Dam is a hydroelectric gravity dam that spans the Yangtze River by the town of Sandouping, in Yiling District, Yichang, Hubei province, central China, downstream of the Three Gorges. The Three Gorges Dam has been the world's largest power station in terms of installed capacity since 2012."], 
        'image': ['https://images.pexels.com/photos/7897564/pexels-photo-7897564.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 'https://images.pexels.com/photos/5102098/pexels-photo-5102098.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 'https://images.pexels.com/photos/5544196/pexels-photo-5544196.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 'https://images.pexels.com/photos/2775742/pexels-photo-2775742.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500', 'https://images.pexels.com/photos/414199/pexels-photo-414199.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500'], 
    }, 

    'Italy': {
        'name': ['Colosseum', 'Florence Duomo Santa Maria del Fiore', 'The Grand Canal in Venice', 'Pompeii and Mount Vesuvius', 'Amalfi Coast'], 
        'description': ["The Colosseum is an oval amphitheatre in the centre of the city of Rome, Italy, just east of the Roman Forum. It is the largest ancient amphitheatre ever built, and is still the largest standing amphitheatre in the world today, despite its age.", "Florence Cathedral, formally the Cattedrale di Santa Maria del Fiore, is the cathedral of Florence, Italy. It was begun in 1296 in the Gothic style to a design of Arnolfo di Cambio and was structurally completed by 1436, with the dome engineered by Filippo Brunelleschi.", "Grand Canal, Italian Canale Grande, main waterway of Venice, Italy, following a natural channel that traces a reverse-S course from San Marco Basilica to Santa Chiara Church and divides the city into two parts. Slightly more than 3 km (2 miles) long and between 30 and 70 metres (100 and 225 feet) wide, the Grand Canal has an average depth of 5 metres (17 feet) and connects at various points with a maze of smaller canals.", "Mount Vesuvius is a somma-stratovolcano located on the Gulf of Naples in Campania, Italy, about 9 km east of Naples and a short distance from the shore. It is one of several volcanoes which form the Campanian volcanic arc.", "The Amalfi Coast is a 50-kilometer stretch of coastline along the southern edge of Italy’s Sorrentine Peninsula, in the Campania region. It’s a popular holiday destination, with sheer cliffs and a rugged shoreline dotted with small beaches and pastel-colored fishing villages. The coastal road between the port city of Salerno and clifftop Sorrento winds past grand villas, terraced vineyards and cliffside lemon groves. "], 
        'image': ['https://images.pexels.com/photos/2940654/pexels-photo-2940654.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 'https://images.pexels.com/photos/3766511/pexels-photo-3766511.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500', 'https://images.pexels.com/photos/621807/pexels-photo-621807.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 'https://images.pexels.com/photos/4215110/pexels-photo-4215110.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 'https://images.pexels.com/photos/632522/pexels-photo-632522.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940'], 
    }, 

    'Turkey': {
        'name': ['Hagia Sophia Mosque', 'Ephesus', 'Cappadocia', 'Topkapi Palace', 'Antalya'], 
        'description': ["Hagia Sophia, officially known as the Holy Hagia Sophia Grand Mosque, and formerly the Church of Hagia Sophia and formerly museum is a Late Antique place of worship in Istanbul, designed by the Greek geometers Isidore of Miletus and Anthemius of Tralles.", "Ephesus was an ancient port city whose well-preserved ruins are in modern-day Turkey. The city was once considered the most important Greek city and the most important trading center in the Mediterranean region. Throughout history, Ephesus survived multiple attacks and changed hands many times between conquerors.", "Cappadocia, a semi-arid region in central Turkey, is known for its distinctive “fairy chimneys,” tall, cone-shaped rock formations clustered in Monks Valley, Göreme and elsewhere. Other notables sites include Bronze Age homes carved into valley walls by troglodytes (cave dwellers) and later used as refuges by early Christians. The 100m-deep Ihlara Canyon houses numerous rock-face churches.", "The Topkapı Palace, or the Seraglio, is a large museum in the east of the Fatih district of Istanbul in Turkey. In the 15th and 16th centuries it served as the main residence and administrative headquarters of the Ottoman sultans.", "Antalya is a Turkish resort city with a yacht-filled Old Harbor and beaches flanked by large hotels. It's a gateway to Turkey's southern Mediterranean region, known as the Turquoise Coast for its blue waters. Remnants remain from Antalya's time as a major Roman port. These include Hadrian’s Gate, built to honor the Roman emperor’s visit in 130 A.D and 2nd-century Hidirlik Tower, with harbor views."], 
        'image': ['https://images.pexels.com/photos/6152260/pexels-photo-6152260.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 'https://images.pexels.com/photos/8887762/pexels-photo-8887762.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500', 'https://images.pexels.com/photos/3889704/pexels-photo-3889704.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 'https://images.pexels.com/photos/604661/pexels-photo-604661.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 'https://images.pexels.com/photos/6531009/pexels-photo-6531009.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940'], 
    }, 

    'Mexico': {
        'name': ['San Miguel de Allende', 'El Malecon', 'Zipolite', 'El Tajin', 'Santa Prisca Church in Taxco'], 
        'description': ["San Miguel de Allende, a colonial-era city in Mexico’s central highlands, is known for its baroque Spanish architecture, thriving arts scene and cultural festivals. In the city’s historic, cobblestoned center lies the neo-Gothic church Parroquia de San Miguel Arcángel, whose dramatic pink towers rise above the main plaza, El Jardín. The Templo de San Francisco church nearby has an 18th-century churrigueresque facade. ", "The Malecón is a broad esplanade, roadway, and seawall that stretches for 8 km along the coast in Havana, Cuba, from the mouth of Havana Harbor in Old Havana, along the north side of the Centro Habana neighborhood and the Vedado neighborhood, ending at the mouth of the Almendares River. ", "Zipolite is a low-key beach resort on Mexico’s Pacific coast in the state of Oaxaca. Stretching between rocky headlands, the long beach is known for its strong surf. Restaurants and bars, many with thatched roofs, line Colonia Roca Blanca. On nearby Mazunte Beach, the Mexican Turtle Center is dedicated to the preservation of sea turtles. East along the coast is Huatulco National Park, with its protected coral reefs.", "El Tajín is a pre-Columbian archeological site in southern Mexico and is one of the largest and most important cities of the Classic era of Mesoamerica. A part of the Classic Veracruz culture, El Tajín flourished from 600 to 1200 CE and during this time numerous temples, palaces, ballcourts, and pyramids were built. ", "The Santa Prisca stands to the southern edge of the Plaza Borda, Taxco's main central square. The church was constructed between 1751 and 1758 funded by Jose de la Borda as a suitable venue for the priest Manuel de la Borda to practice his faith. ... The main portal of the church has a representation Assumption of Mary."], 
        'image': ['https://images.pexels.com/photos/4317340/pexels-photo-4317340.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 'https://images.pexels.com/photos/1076240/pexels-photo-1076240.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 'https://images.pexels.com/photos/189349/pexels-photo-189349.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 'https://images.pexels.com/photos/7375099/pexels-photo-7375099.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500', 'https://images.pexels.com/photos/3766511/pexels-photo-3766511.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940'], 
    }, 

    'Thailand': {
        'name': ['Railay Beach', 'Koh Phi Phi', 'The Grand Palace, Bangkok', 'Sukhothai Old City', 'Historic City of Ayutthaya'], 
        'description': ["Railay, also known as Rai Leh, is a small peninsula between the city of Krabi and Ao Nang in Thailand. It is accessible only by boat due to high limestone cliffs cutting off mainland access.", "The Phi Phi Islands are an island group in Thailand between the large island of Phuket and the Straits of Malacca coast of Thailand. The islands are administratively part of Krabi Province.", "The Grand Palace is a complex of buildings at the heart of Bangkok, Thailand. The palace has been the official residence of the Kings of Siam since 1782. The king, his court, and his royal government were based on the grounds of the palace until 1925.", "Sukhothai was the political and administrative capital of the first Kingdom of Siam in the 13th and 15th centuries. Si Satchanalai was the spiritual center of the kingdom and the site of numerous temples and Buddhist monasteries. Si Satchanalai was also the centre of the all-important ceramic export industry.", "The Historic City of Ayutthaya, founded in 1350, was the second capital of the Siamese Kingdom.  It flourished from the 14th to the 18th centuries, during which time it grew to be one of the world’s largest and most cosmopolitan urban areas and a center of global diplomacy and commerce. Ayutthaya was strategically located on an island surrounded by three rivers connecting the city to the sea. This site was chosen because it was located above the tidal bore of the Gulf of Siam as it existed at that time, thus preventing attack of the city by the sea-going warships of other nations. The location also helped to protect the city from seasonal flooding."], 
        'image': ['https://images.pexels.com/photos/9656583/pexels-photo-9656583.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 'https://images.pexels.com/photos/8599622/pexels-photo-8599622.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 'https://images.pexels.com/photos/5825366/pexels-photo-5825366.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 'https://images.pexels.com/photos/4245826/pexels-photo-4245826.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 'https://images.pexels.com/photos/301469/pexels-photo-301469.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940'], 
    }, 

    'Germany': {
        'name': ["Berlin's Brandenburg Gate", 'Cologne Cathedral', 'The Black Forest', 'The Ultimate Fairytale Castle: Neuschwanstein', 'Miniatur Wunderland and the Historic Port of Hamburg'], 
        'description': ["The Brandenburg Gate is one of the most iconic sights in today’s vibrant Berlin. More than just Berlin’s only surviving historical city gate, this site came to symbolise Berlin’s Cold War division into East and West – and, since the fall of the Wall, a reunified Germany. Architecturally, the sandstone Brandenburg Gate also represents one of the earliest and most attractive examples of a neo-classical building in Germany.", "Cologne Cathedral is a Catholic cathedral in Cologne, North Rhine-Westphalia. It is the seat of the Archbishop of Cologne and of the administration of the Archdiocese of Cologne. It is a renowned monument of German Catholicism and Gothic architecture and was declared a World Heritage Site in 1996.", "The Black Forest is a mountainous region in southwest Germany, bordering France. Known for its dense, evergreen forests and picturesque villages, it is often associated with the Brothers Grimm fairy tales. It's renowned for its spas and the cuckoo clocks produced in the region since the 1700s. The region’s largest town, Freiburg, is filled with Gothic buildings and surrounded by vineyards.", "Set amidst a breathtaking setting, Neuschwanstein Castle is one of Germany's most romantic and famous attractions. Built from 1869 to 1886 under King Ludwig II, the palace also known as The Sleeping Beauty Castle is located near the village of Hohenschwangau and the town of Füssen, by the Austrian border in Bavaria.", "Miniatur Wunderland (German for 'miniature wonderland') is a model railway and miniature airport attraction in Hamburg, Germany, the largest of its kind in the world. The railway is located in the historic Speicherstadt neighbourhood of the city."], 
        'image': ['https://images.pexels.com/photos/3661973/pexels-photo-3661973.png?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 'https://images.pexels.com/photos/161849/cologne-dom-night-architecture-161849.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 'https://images.pexels.com/photos/1367192/pexels-photo-1367192.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 'https://images.pexels.com/photos/3526085/pexels-photo-3526085.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500', 'https://images.pexels.com/photos/167676/pexels-photo-167676.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940'], 
    }, 

    'United Kingdom': {
        'name': ['Tower of London', 'Stonehenge', 'The Roman Baths and Georgian City of Bath', 'The Cotswolds', 'York Minster and Historic Yorkshire'], 
        'description': ["The Tower of London, officially Her Majesty's Royal Palace and Fortress of the Tower of London, is a historic castle on the north bank of the River Thames in central London.", "Stonehenge is a prehistoric monument on Salisbury Plain in Wiltshire, England, two miles west of Amesbury. It consists of an outer ring of vertical sarsen standing stones, each around 13 feet high, seven feet wide, and weighing around 25 tons, topped by connecting horizontal lintel stones.", "The Roman Baths are a well-preserved thermae in the city of Bath, Somerset, England. A temple was constructed on the site between 60-70AD in the first few decades of Roman Britain. Its presence led to the development of the small Roman urban settlement known as Aquae Sulis around the site.", "Comes from the name of an Anglo-Saxon chieftain named Cod in the 12th century that owned high land or wold- hence Cod's wold and eventually became Cotswold. The Cotswolds are sometimes known as King Cod's land.", "The Cathedral and Metropolitical Church of Saint Peter in York, commonly known as York Minster, is the cathedral of York, England, and is one of the largest of its kind in Northern Europe."], 
        'image': ['https://images.pexels.com/photos/258117/pexels-photo-258117.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 'https://images.pexels.com/photos/1448136/pexels-photo-1448136.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 'https://images.pexels.com/photos/4577651/pexels-photo-4577651.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', 'https://images.pexels.com/photos/8202753/pexels-photo-8202753.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500', 'https://images.pexels.com/photos/6140470/pexels-photo-6140470.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940'], 
    }, 
}; 
